export const GAME_ACTIONS = {
  eat: {
    hungerIncrease: 20,
    experienceGain: 10,
    energyDecrease: 5,
    emoji: '🍕',
    label: 'Mat',
  },
  play: {
    happinessIncrease: 20,
    experienceGain: 15,
    hungerDecrease: 5,
    energyDecrease: 10,
    emoji: '🎮',
    label: 'Lek',
  },
  sleep: {
    energyIncrease: 30,
    experienceGain: 5,
    hungerDecrease: 10,
    emoji: '😴',
    label: 'Sov',
  },
  exercise: {
    healthIncrease: 15,
    experienceGain: 20,
    hungerDecrease: 15,
    energyDecrease: 20,
    happinessIncrease: 10,
    emoji: '🏃',
    label: 'Träna',
  },
  pet: {
    happinessIncrease: 15,
    healthIncrease: 5,
    experienceGain: 8,
    emoji: '❤️',
    label: 'Klappa',
  },
  medicine: {
    healthIncrease: 30,
    happinessDecrease: 10,
    experienceGain: 5,
    emoji: '💊',
    label: 'Medicin',
  },
} as const;
